apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  containers:
  - name: producer
    image: su9denly/my-producer:latest
    env:
    - name: KAFKA_BOOTSTRAP_SERVER
      value: "kafka-0.kafka.default.svc.cluster.local:9092"

# apiVersion: v1
# kind: Pod
# metadata:
#   name: kafka-producer
# spec:
#   containers:
#   - name: producer
#     image: su9denly/my-producer:latest
#     ports:
#     - containerPort: 8080
#     env:
#     - name: KAFKA_BOOTSTRAP_SERVER
#       value: "kafka:9092"
