name: Docker Build and Publish

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build-and-publish-consumer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the latest tag
      id: tag
      run: echo "::set-output name=TAG::$(git describe --abbrev=0 --tags)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile-consumer
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONSUMER_REPOSITORY_NAME }}:${{ steps.tag.outputs.TAG }}
